### ISSUE TITLE
[Proposal] Remove transparent color variables

### ISSUE THREAD

**Issue by sineway** [FirefoxUX/photon-colors#16]
How variables could be defined:
```css
:root {
  --blue-50: 210, 100%, 51%;
}
```
How variables could be used:
```css
.button:focus {
    box-shadow: 0 0 0 2px hsl(var(--blue-50), .3);
}
```
